
// Code generated by MetaFFI. DO NOT EDIT.
// Host code for {{.IDLFilenameWithExtension}}
package metaffi_host;

import java.io.*;
import java.util.*;
import metaffi.*;



public class Any
{
	private metaffi.MetaFFIHandle this_instance;
	private static metaffi.MetaFFIBridge metaffiBridge = new metaffi.MetaFFIBridge();

	
	

	
	
	public Any( ) throws MetaFFIException
	{
		long xcall_params = metaffiBridge.alloc_cdts((byte)0, (byte)1);
		long return_valuesCDTS = metaffiBridge.get_pcdt(xcall_params, (byte)0);


		

		
		metaffiBridge.xcall_no_params_ret(validation.Any_AnyID, xcall_params);


		this.this_instance = (metaffi.MetaFFIHandle)metaffiBridge.cdts_to_java(return_valuesCDTS, 1)[0];
	}
	

	
	
	@Override
	public void finalize()
	{
		// TODO: Delete reference to the object in the objects table
	}
	


	
}
