#!/usr/bin/env bash
# Generate Go gRPC stubs from benchmark.proto
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

mkdir -p "$SCRIPT_DIR/pb"

protoc \
  --go_out="$SCRIPT_DIR/pb" --go_opt=paths=source_relative \
  --go-grpc_out="$SCRIPT_DIR/pb" --go-grpc_opt=paths=source_relative \
  -I "$SCRIPT_DIR" \
  "$SCRIPT_DIR/benchmark.proto"

echo "Go stubs generated in $SCRIPT_DIR/pb/"

# Java stubs are generated by Gradle's protobuf plugin.
# Build the Java server with:
#   cd server && gradle shadowJar
echo "To build Java gRPC server: cd $SCRIPT_DIR/server && gradle shadowJar"
